# Generated by Django 3.2.5 on 2022-12-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_sitemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statuscode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('csvfile', models.FileField(upload_to='dynamic/')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
